___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [8]:
print(f'Версія бібліотеки NumPy: {np.__version__}\n')

print('Конфігурація бібліотеки NumPy:')
np.show_config()

Версія бібліотеки NumPy: 1.18.5

Конфігурація бібліотеки NumPy:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/anias/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/anias/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/anias/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelS

Створити вектор з 10 елементів, заповнений одиницями:

In [14]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [15]:
x = np.array(range(11))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [19]:
m_5_5 = np.zeros((5,5))
m_5_5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [12]:
vector_20 = np.random.randint(-20,20,(20))
print(f'Вектор з цілими числами: {vector_20}')

nonzero_vector_20 = np.nonzero(vector_20)
print(f'Індекси ненульових елементів вектора: {nonzero_vector_20}')


Вектор з цілими числами: [ 16   5   8  -8   1  -8   8 -16  -1  -6  15 -11  11 -12 -20  -4   5 -14
 -13  12]
Індекси ненульових елементів вектора: (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [13]:
mean_vector_20 = np.mean(vector_20)
print(f'Середнє значення вектора: {mean_vector_20}')

median_vector_20 = np.median(vector_20)
print(f'Медіана вектора: {median_vector_20}')

nanstd_vector_20 = np.nanstd(vector_20)
print(f'Стандартне відхилення вектора: {nanstd_vector_20}')

Середнє значення вектора: -1.6
Медіана вектора: -2.5
Стандартне відхилення вектора: 10.818502669038816


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [23]:
m_4_2 = np.random.randint(-20,20,(4,2))
print(f'Матриця 4х2: \n {m_4_2} \n')

m_2_2 = np.random.randint(-1,1,(2,2))
print(f'Матриця 2х2: \n {m_2_2} \n')

dot_2m = np.dot(m_4_2, m_2_2)
print(f'Результат множення 2-х матриць: \n {dot_2m} \n')

Матриця 4х2: 
 [[  6 -11]
 [-10 -18]
 [  7 -17]
 [-14  14]] 

Матриця 2х2: 
 [[ 0 -1]
 [-1 -1]] 

Результат множення 2-х матриць: 
 [[ 11   5]
 [ 18  28]
 [ 17  10]
 [-14   0]] 



Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [24]:
reshape_vector=dot_2m.reshape((dot_2m.size))  #(1, dot_2m.size)

print(f'Перетворюємо матрицю у вектор: {reshape_vector}')

max_vector=np.max(reshape_vector)
print(f'Максимальне значення вектора: {max_vector}')

min_vector=np.min(reshape_vector)
print(f'Мінімальне значення вектора: {min_vector}')

reshape_vector[reshape_vector==max_vector]=0
print(f'Максимальне значення вектора замінюємо на нуль: {reshape_vector}')

Перетворюємо матрицю у вектор: [ 11   5  18  28  17  10 -14   0]
Максимальне значення вектора: 28
Мінімальне значення вектора: -14
Максимальне значення вектора замінюємо на нуль: [ 11   5  18   0  17  10 -14   0]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [41]:
# измеряется теснота связей между двух векторов (отражает зашумленность линейной зависимости)
corrcoef1_dot_2m = np.corrcoef(dot_2m[0], dot_2m[1])
corrcoef2_dot_2m = np.corrcoef(dot_2m[0], dot_2m[2])
corrcoef3_dot_2m = np.corrcoef(dot_2m[0], dot_2m[3])
print(f'Кореляцію 1-го рядка матриці к 2-му: \n {corrcoef1_dot_2m}')
print(f'Кореляцію 1-го рядка матриці к 3-му: \n {corrcoef2_dot_2m}')
print(f'Кореляцію 1-го рядка матриці к 4-му: \n {corrcoef3_dot_2m}')

Кореляцію 1-го рядка матриці к 2-му: 
 [[1. 1.]
 [1. 1.]]
Кореляцію 1-го рядка матриці к 3-му: 
 [[1. 1.]
 [1. 1.]]
Кореляцію 1-го рядка матриці к 4-му: 
 [[ 1. -1.]
 [-1.  1.]]


Дано матрицю. Знайти ранг матриці:

In [29]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

rank_a = np.linalg.matrix_rank(a) # макс кол-во линейно-независемых столбцов (строк).
rank_a                            # линейно-независимый вектор нельзя выразить через др вектора

3

Знайти визначник матриці:

In [30]:
det_a = np.linalg.det(a) # подходит для квадратных матриц
det_a

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [31]:
np.linalg.eig(a) # подходит для квадратных матриц

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [46]:
a = np.random.randint(0,10,50)
print(f'Масив: {a}')

bincount_a = np.bincount(a).argmax() # bincount -возвращает количество вхождений значений в массиве
print(f'Число, що найчастіше зустрічається в масиві: {bincount_a}')

Масив: [5 2 4 4 6 3 4 9 8 4 4 0 7 7 4 1 1 9 1 1 2 6 2 5 5 5 3 1 0 7 8 0 9 8 2 5 6
 2 0 8 4 0 2 3 3 5 2 7 8 5]
Число, що найчастіше зустрічається в масиві: 2


Виведіть лише парні числа, що діляться на 5:

In [39]:
a = np.random.randint(0,10,50)
print(a)

a[(a % 2 == 0) & (a % 5 == 0)]

[5 1 9 9 1 9 2 9 3 6 9 3 1 7 8 2 7 5 9 5 8 7 8 9 6 1 1 5 7 1 9 4 1 8 7 5 4
 3 0 9 0 5 5 1 8 1 0 4 4 6]


array([0, 0, 0])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [36]:
array1 = np.array([[2, 5],[1, -10]])
array2 = np.array([1,3])

solve_2 = np.linalg.solve(array1, array2)
print(solve_2)

[ 1.  -0.2]
